### ISSUE TITLE
PRACTICA #5 MAGALY NICOLAS SANCHEZ 

### ISSUE THREAD

**Issue by magaly1311** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-magaly1311#2]
[PRACTICA 5 TOPICOS AVANZADOS DE PROGRAMACION MAGALY NICOLAS SANCHEZ.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-magaly1311/files/8346719/PRACTICA.5.TOPICOS.AVANZADOS.DE.PROGRAMACION.MAGALY.NICOLAS.SANCHEZ.pdf)

**Comment by JudithReynaCS** [comment]
Calificación:20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
